#pragma once
#define PHX_VERSION_STRING "1.0.2"
#define PHX_BUILD_CODE "FINAL"
#define PHX_BUILD_NAME "Robust Bank-Load Watchdog Fix"
#define PHX_FULL_VERSION "Project Phoenix v" PHX_VERSION_STRING " " PHX_BUILD_CODE
#define PHX_BANK_FORMAT_VERSION 15
#define PHX_MULTISAMPLE_FORMAT_VERSION 10
